version: '3'
services:
  maria_db:
    container_name: maria_db
    image: mariadb:10.2.11
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log_warnings=1
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./server/db/sqls:/docker-entrypoint-initdb.d
  server:
    container_name: flask
    tty: true
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - maria_db
    command: sh -c "python wait.py && python app.py"
  client:
    container_name: vue
    tty: true
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: yarn serve
